name: TestWorkflow

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
     
      - name: Install dependencies
        run: dotnet restore ./GTC/GTC.sln
      - name: Build
        run: dotnet build ./GTC/GTC.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test ./GTC/GTC.sln --no-restore --verbosity normal --no-restore

